spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa


logging:
  level:
    org.hibernate:
        SQL: DEBUG
        type: TRACE